### PR TITLE
Feature/replace sdk to etherjs

### PR DESCRIPTION
**Pull request by NailKhalimov**
https://bunzz-test.atlassian.net/jira/software/projects/BUNZZ1/boards/2?selectedIssue=BUNZZ1-298

### CODE REVIEW

**Comment by smart-hede** [comment]
image
Hi, @NailKhalimov 
Looks good. I think you almost done.

But the price doesn't seem to be correct.
You maybe need to use BigNumber of ether.js
This doesn't look good.
```
  // Get cost from contract
  const getCost = async (contract: Contract) => {
    const res = await contract.publicCost();
    setCost((Number(res._hex) / 10 ** 18).toString());
  };
```
I suggest you use BigNumber

**Comment by smart-hede** [comment]
image
In my side, minting tx is failed.
I think that is related with the large (incorrect) price. Because I set the price 10.

**Comment by NailKhalimov** [comment]
@smart-ticky 
Make sure you followed readme. Error message says minting is paused.
Please check your contract is paused or not.

**Comment by smart-hede** [comment]
@NailKhalimov 
Okay, I unpaused the smart contract and that worked well.

**Comment by NailKhalimov** [comment]
@smart-ticky 
Then, please approve and merge PR!
Thanks👍

**Pull request merged**
